//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/awp_katkat.html
halflife.wad
decals.wad
cs_cbble.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
cs_bdog.wad
maps/awp_katkat.bsp
